FROM golang:1.15.6-alpine3.12

ENV ENV test

RUN apk update && \
    apk add --no-cache curl gcc musl-dev git && \
    go get -u github.com/rubenv/sql-migrate/... && \
# alpineだとgoのバイナリが実行できない問題があるらしいので対応(https://blog.kozakana.net/2019/09/go-binary-not-found/)
    mkdir /lib64 && \
    ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

WORKDIR /usr/local/workout/

EXPOSE 8081

CMD ./script/test.sh